### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by jakubszalek** [adamborowski/react-arch-demo#5]
Hi Adam!

Thank you for taking the time to complete our test and to agree to provide some improvements.

It is a fundamental part of the interview process. There are no time constraints from my side, so that you can provide fixes and discussion on your own time, at your own pace.

Cheers, 
Jakub

**Comment by adamborowski** [comment]
Hey @jakubszalek , 
We have three options to go:
1. I can implement suggestions "as is" just to address the issues and proceed
2. I can argue on some points mostly related to optimization or complexity, but this might be more appropriate in later conversation
3. I can change the approach (to demonstrate architectural ideas that apply to more complex situations ie supporting multiple IO) and just provide the code that is simple and clean, does the job, without extra footprint and assumptions.

I prefer 3) as a compromise between 1) and 2) and later on we will talk about extra renders or abstraction layers

What do you prefer?

**Comment by mrcodegit** [comment]
Hey Adam, please go with option number 1

**Comment by adamborowski** [comment]
Hello @mrcodegit @jakubszalek 

I provided fixes for two issues as pull requests,
for all other points, I just created a new branch:
[minimalistic version](https://github.com/adamborowski/react-arch-demo/tree/minimalistic-version)
[main page file](https://github.com/adamborowski/react-arch-demo/blob/minimalistic-version/src/features/repositories/pages/search/RepositorySearchPage.connected.tsx)

Please review it - it's much smaller and it should have all suggestions implemented, starting from sticking to GQL only.

**Comment by mrcodegit** [comment]
Thank you @adamborowski, on it
