### ISSUE TITLE
Errors in browser's console during runtime

### ISSUE THREAD

**Issue by jakubszalek** [adamborowski/react-arch-demo#6]
I noticed many errors logged into browser's console during app loading.
They seem to be related with translations.
Please take a look what might be an issue.

**Comment by adamborowski** [comment]
This is a desired behavior of react-intl.
There are translations missing for any language except english (ie PL).
Those warnings are logged only in the development mode, there are no warnings in production.

More details:
https://github.com/formatjs/formatjs/issues/465

My suggestion is to leave as is to not change default devex of react-intl.
Possible solution, not recommended by me (from the discussion mentioned above):
```tsx
<IntlProvider
      locale={navigator.language}
      defaultLocale="en"
      onError={(err) => {
        if (err.code === "MISSING_TRANSLATION") {
          // NO-OP
          return;
        }
        throw err;
      }}
    >
...
`

**Comment by mrcodegit** [comment]
@adamborowski thanks for explaining, no further actions required
